### ISSUE TITLE
As a new user navigating the website, I want to be able to see a loading screen after choosing my food options. This loading screen will lead me to choose my 5 favorable restaurants.

### ISSUE THREAD

**Issue by ramikham** [UB-CSE/course-project-team-eats#28]
Acceptance Test:
1. After choosing the food options, a loading screen appears
2. The loading screen should take the users to the next page, where they can choose their top 5 restaurants

**Comment by jtdilapo** [comment]
***Team member dropped course***

Moving back to Backlog
