### ISSUE TITLE
Using Heroku, connect example webpage's frontend with backend through multiple bottle routes

### ISSUE THREAD

**Issue by jtdilapo** [UB-CSE/course-project-team-eats#88]
User Story #69

Task Tests:

Developer:

1) Navigate to example website directory
2) Open DBfuncts.py
3) Change any functionality as needed
4) In Terminal under example website directory run the following commands:
5)git add -A
6)git commit -m "added functionality"
7) git push heroku master
8) View updated changes as made

User:
1) Go to https://ancient-hollows-62522.herokuapp.com/ to view the live app
2) Type test into Input: tomato
3) View output which is: tomato basil bisque,
4) Type test into Input: steak
5) View output which is: 12oz wagyu strip steak,Grade 9 American Wagyu,steak,mozzarella, fontinella, gorgonzola, cajun tenderloin, caramelized onions, banana peppers, thyme salt,steak skewer,soy marinated tenderloin skewer, caramelized onions, wild mushrooms, snap peas, soy gastrique

2nd Task Test:
Test Algorithm
1) type in test1 into input and click Test Algorithm Button
2) view results of running the algorithm on test1 : 'Jasmines'
3) type in test2 into input and click Test Algorithm Button
4) view results of running the algorithm on test2: 'Kyoto Japanese Restaurant'

**Comment by anarghya-das** [comment]
Modify the page to either remove the Test Algorithm button or add the description about it in the task test.
